- name: Installing HAProxy conf for rsyslog
  template:
   src: /var/www/haproxy-wi/app/scripts/ansible/roles/haproxy/templates/haproxy_rsyslog.conf.j2
   dest: /etc/rsyslog.d/49-haproxy.conf
   force: yes
  ignore_errors: yes
  notify: restart rsyslog

- name: Installing HAProxy conf for logrotate on EL
  template:
    src: /var/www/haproxy-wi/app/scripts/ansible/roles/haproxy/templates/logrotate.conf.j2
    dest: /etc/logrotate.d/haproxy.conf
    force: no
  when: ansible_os_family == "RedHat"
  ignore_errors: yes

- name: Installing HAProxy conf for logrotate on Debian
  template:
    src: /var/www/haproxy-wi/app/scripts/ansible/roles/haproxy/templates/logrotate-debian.conf.j2
    dest: /etc/logrotate.d/haproxy-roxy-wi
    force: no
  when: ansible_os_family == "Debian"
  ignore_errors: yes
