---      
- name: check if HAProxy is installed
  package_facts:
    manager: "auto"

- name: populate service facts
  service_facts:

- include: configure.yml

- include: installation.yml

- include: logs.yml

- name: Add syn_flood tasks
  include: syn_flood.yml
  when: (SYN_FLOOD is defined) and (SYN_FLOOD|length > 0)  
    