---
nginx_exporter_user: nginx_exporter
nginx_exporter_user_manage: true
nginx_exporter_group: nginx_exporter
nginx_exporter_group_manage: true

nginx_exporter_version: "0.5.0"
nginx_exporter_platform_suffix: "linux_amd64"
nginx_exporter_platform_suffix_alt: "linux-amd64"

nginx_exporter_signature: "nginx-prometheus-exporter_{{ nginx_exporter_version }}_{{ nginx_exporter_platform_suffix }}"
nginx_exporter_signature_alt: "nginx-prometheus-exporter-{{ nginx_exporter_version }}-{{ nginx_exporter_platform_suffix_alt }}"
nginx_exporter_dist_dir: "{{ prometheus_exporter_dist_dir }}/{{ nginx_exporter_signature }}"
nginx_exporter_dist_dir_alt: "{{ prometheus_exporter_dist_dir }}/{{ nginx_exporter_signature_alt }}"
nginx_exporter_tarball_url: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ nginx_exporter_version }}/{{ nginx_exporter_signature }}.tar.gz"
nginx_exporter_tarball_url_alt: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ nginx_exporter_version }}/{{ nginx_exporter_signature_alt }}.tar.gz"
nginx_exporter_program: "{{ prometheus_exporter_dir }}/nginx_exporter"
nginx_exporter_home: "/var/lib/nginx_exporter"
nginx_exporter_home_manage: true
nginx_exporter_options:
  - '-nginx.retries 32768'
  - '-nginx.scrape-uri http://localhost/nginx_stats'

nginx_exporter_config_file: /etc/default/nginx_exporter
nginx_exporter_pid_path: "/var/run"
nginx_exporter_log_path: "/var/log/nginx_exporter"

nginx_exporter_service_manage: true
nginx_exporter_service_enable: true
nginx_exporter_service_state: started
nginx_exporter_service_notify: true
