---        
- name: install the latest version of Keepalived
  yum:
    name: 
      - keepalived
    state: latest
  when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == 'CentOS'
  environment:
    http_proxy: "{{PROXY}}"
    https_proxy: "{{PROXY}}"

    
- name: Install keepalived
  apt:
    name: 
      - keepalived
    state: present
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Ubuntu'
  environment:
    http_proxy: "{{PROXY}}"
    https_proxy: "{{PROXY}}"

  
- name: Copy keepalived configuration in place.
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
  notify: restart keepalived
  
  
- name: Enable and start service keepalived
  service:
    name: keepalived
    daemon_reload: yes
    state: started
    enabled: yes
  ignore_errors: yes
    