- hosts: "{{ variable_host }}"
  become: yes
  become_method: sudo
  tasks:
  - name: Set SSH port
    set_fact:
      ansible_port: "{{SSH_PORT}}"

  - name: Open stat port for iptables
    iptables:
      chain: INPUT
      destination_port: "9650"
      jump: ACCEPT
      protocol: tcp
    ignore_errors: yes

  roles:
  - role: keepalived_exporter
    environment:
      http_proxy: "{{PROXY}}"
      https_proxy: "{{PROXY}}"
