---
- name: Install common role
  hosts: "{{ variable_host }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - role: nginx_common
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"

  tags:
    - system
    - docker

- name: Install docker
  hosts: "{{ variable_host }}"
  become: yes
  gather_facts: yes
  roles:
    - role: docker
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"
    - role: nginx_docker
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"
  tags:
    - docker

- name: Install system role
  hosts: "{{ variable_host }}"
  become: yes
  become_method: sudo
  tasks:
  - name: Add syn_flood tasks
    include: haproxy/tasks/syn_flood.yml
    when: (SYN_FLOOD is defined) and (SYN_FLOOD|length > 0)
  - name: Install nginx for Centos Stream 9
    package:
      name: nginx
      state: present
    when: ansible_facts['distribution_major_version'] == '9'
    tags:
      - system
  roles:
    - role: nginxinc.nginx
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"
      when: ansible_facts['distribution_major_version'] != '9'
  tags:
    - system

- name: Set correct owner
  hosts: "{{ variable_host }}"
  become: yes
  tasks:
    - name: Set
      shell: "chown nginx:nginx -R {{ nginx_dir }}"

