---
- name: Install common role
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - role: service_common
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"

  tags:
    - system
    - docker

- name: Install docker
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: docker
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"
    - role: service_docker
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"
      vars:
        image_name: nginx
        cont_etc_dir: "/etc/nginx"
  tags:
    - docker

- name: Install system role
  hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Add syn_flood tasks
    include_tasks: haproxy/tasks/syn_flood.yml
    when: (SYN_FLOOD is defined) and (SYN_FLOOD|length > 0)
  - name: Install nginx for Centos Stream 9
    package:
      name: nginx
      state: present
    when: ansible_facts['distribution_major_version'] == '9'
    tags:
      - system
  roles:
    - role: nginxinc.nginx
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"
      when: ansible_facts['distribution_major_version'] != '9'
  tags:
    - system

- name: "Set {{ ansible_user }} owner to {{ service_dir }}"
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: "Set {{ ansible_user }} owner to {{ service_dir }}"
      file:
        path: "{{ service_dir }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        state: directory
        recurse: true
        mode: 0775
  tags:
    - system
    - docker

