---
- name: Install common role
  hosts: "{{ variable_host }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - role: nginx_common
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"

  tags:
    - system
    - docker

- name: Install docker
  hosts: "{{ variable_host }}"
  gather_facts: yes
  roles:
    - role: docker
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"
    - role: nginx_docker
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"
  tags:
    - docker

- name: Install system role
  hosts: "{{ variable_host }}"
  become: yes
  become_method: sudo
  tasks:
  - name: Add syn_flood tasks
    include: haproxy/tasks/syn_flood.yml
    when: (SYN_FLOOD is defined) and (SYN_FLOOD|length > 0)
  roles:
    - role: nginxinc.nginx
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"
  tags:
    - system
