---
- name: Ensuring nginx directories exist
  file:
    path: "/etc/nginx"
    state: "directory"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: "0770"
  become: true
  ignore_errors: yes

- name: Ensuring conf.d directories exist
  file:
    path: "{{ nginx_dir }}"
    state: "directory"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: "0770"
  become: true
  ignore_errors: yes

- name: Ensuring sites-enabled directories exist
  file:
    path: "/etc/nginx/sites-enabled"
    state: "directory"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: "0770"
  become: true
  ignore_errors: yes

- name: Ensuring log directories exist
  file:
    path: "/var/log/nginx/"
    state: "directory"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: "0770"
  become: true
  ignore_errors: yes

- name: Create Nginx
  docker_container:
    name: "{{ CONT_NAME }}"
    image: "nginx"
    recreate: yes
    network_mode: host
    volumes:
      - "/etc/nginx/:/etc/nginx/:rw"
      - "/tmp:/tmp:ro"
      - "/var/log:/var/log:rw"
  vars:
    ansible_python_interpreter: /usr/bin/python3
